version: "3.9"

services:
  fuel-alert:
    build: .
    container_name: fuel-alert
    restart: always
    ports:
      - "46200:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
